version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread --log-file=- --reload --timeout 300
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod

volumes:
  postgres_data_prod:
